### PR TITLE
Added unzip feature

### PR DESCRIPTION
**Pull request by nschcolnicov**
## PR checklist
CHANGE SUMMARY
- Adding the possibility of using gzipped fasta and gtf files as input reference files.
- I tested running this with the test_full dataset using a gzipped fasta and gtf file and it passed, I also run the test profile using the regular genome files and it passed too.
- Added the unzip module using the nf-core tooling (nf-core modules install unzip)
- I ran the nf-core lint command, and then nf-core lint --fix files_unchanged, there is only one issue remaining, which is unrelated to these changes:
image
image

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnavar/tree/master/.github/CONTRIBUTING.md)
  - [x] If necessary, also make a PR on the nf-core/rnavar _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by maxulysse** [comment]
It feels like you have a couple of template update in your PR, can you check that up?

**Comment by nschcolnicov** [comment]
> It feels like you have a couple of template update in your PR, can you check that up?

@maxulysse I pulled the latest changes from dev, let me know if there is anything else needed

**Review by maxulysse — APPROVED** [review]

**Comment by nschcolnicov** [comment]
@maxulysse I see that the only check missing is the "prettier" one, I have run the command prettier --check in the branch and I don't see any issues:
image

Is there a way of knowing what is causing this failed test?

**Comment by maxulysse** [comment]
@nf-core-bot fix linting pretty please

**Comment by maxulysse** [comment]
> @maxulysse I see that the only check missing is the "prettier" one, I have run the command prettier --check in the branch and I don't see any issues:
> image
> 
> Is there a way of knowing what is causing this failed test?

It should be good now

**Pull request merged**
